spring.application.name=auction-api

# Default Profile (Override with SPRING_PROFILES_ACTIVE=prod or --spring.profiles.active=prod)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Common Default Pool Configuration
app.datasource.pool-size=${APP_DATASOURCE_POOL_SIZE:10}
app.datasource.connection-timeout=30s
app.datasource.idle-timeout=10m

# Common Actuator Health Endpoint Configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always